/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package taixe;

import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.border.TitledBorder;

/**
 *
 * @author tran minh hai
 */
public class TaiXe extends javax.swing.JFrame {
    private String tk=null;
    private String mk=null;
    private String txid=null;
    private String hoten=null;
    private String gioitinh=null;
    private String ngaysinh=null;
    private String diachi=null;
    private String sdt=null;
    private String ttt=null;
    private String diem=null;
    private String ip=null;
    private String tbatdau=null;
    private String tketthuc=null;
    private DataInputStream din=null;
    private DataOutputStream dout=null;
    private String bien=null;
    private String tkkh="";
    private String diemdi=null;
    private String diemden=null;
    /**
     * Creates new form TaiXe
     * @param Txid
     * @param Hoten
     * @param Gioitinh
     * @param Ngaysinh
     * @param Ttt
     * @param Sdt
     * @param Tk
     * @param Diachi
     * @param Diem
     * @param Din
     * @param Dout
     * @param Mk
     * @param Bien
     * @param Ip
     */
    public TaiXe(String Txid,String Hoten,String Gioitinh,String Ngaysinh,String Diachi,String Sdt,String Ttt,String Tk,String Diem,DataInputStream Din,DataOutputStream Dout,String Mk,String Bien,String Ip) {
        
        initComponents();
        ip = Ip;
        txid = Txid;
        hoten = Hoten;
        gioitinh = Gioitinh;
        ngaysinh = Ngaysinh;
        diachi = Diachi;
        sdt = Sdt;
        ttt = Ttt;
        tk = Tk;
        diem = Diem;
        din = Din;
        dout = Dout;
        mk = Mk;
        bien = Bien;
        TitledBorder title1 = new TitledBorder("Thông Tin Tài Xế");
        jPanel1.setBorder(title1);
        TitledBorder title2 = new TitledBorder("Lộ Trình");
        jPanel2.setBorder(title2);
        jLabel9.setText(tk);
        jLabel12.setText(txid);
        jLabel10.setText(hoten);
        
        Thread readData = new Thread(new ReadData());
        readData.start();
    }
    
    public class ReadData implements Runnable {

        @Override
        public void run() {
            String s1=null;
            String[] s2;
            try {
                ChapNhanHoacTuChoi ct = null;
                while(true) {
                    s1 = din.readUTF();
                    
                    s2 = s1.split("&");
                    if(s2[0].equalsIgnoreCase("kiemtratien")) {
                        JOptionPane.showMessageDialog(null,"Ban co: "+s2[1]+" d trong tai khoan");
                    }
                    if(s2[0].equalsIgnoreCase("yeucau")) {
                        diemdi = s2[3];
                        diemden = s2[4];
                        ct = new ChapNhanHoacTuChoi(s2[1],s2[2],txid,hoten,dout);
                        ct.setVisible(true);
                    }
                    if(s1.equalsIgnoreCase("huybo")) {
                        ct.dispose();
                    }
                    if(s2[0].equalsIgnoreCase("taikhoankhachhang")) {
                        tkkh = s2[1];
                    }
                    if(s2[0].equalsIgnoreCase("capnhattentaixe")) {
                        jLabel10.setText(s2[1]);
                    }
                    if(s2[0].equalsIgnoreCase("danhgia")) {
                        jTextField2.setText(String.valueOf(s2[1]));
                    }
                }
            } catch (IOException ex) {
                Logger.getLogger(TaiXe.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField3 = new javax.swing.JTextField();
        btn_ketThuc = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btn_batDau = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jToolBar1 = new javax.swing.JToolBar();
        jButton2 = new javax.swing.JButton();
        btn_capNhatThongTin = new javax.swing.JButton();
        btn_kiemTra$ = new javax.swing.JButton();
        btn_themXe = new javax.swing.JButton();
        btn_xoaXe = new javax.swing.JButton();
        btn_dangXuat = new javax.swing.JButton();

        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });

        btn_ketThuc.setText("Ket Thuc");
        btn_ketThuc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ketThucActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel1.setText("Tài khoản");

        jLabel2.setText("Họ tên");

        jLabel9.setText("jLabel9");

        jLabel10.setText("jLabel10");

        jLabel11.setText("ID");

        jLabel12.setText("jLabel12");

        jLabel3.setText("Chi tiết");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addGap(360, 360, 360))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(165, 165, 165)
                        .addComponent(jLabel7)
                        .addGap(198, 198, 198)
                        .addComponent(jLabel8)
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel10)
                    .addComponent(jLabel3))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        btn_batDau.setText("Bắt đầu");
        btn_batDau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_batDauActionPerformed(evt);
            }
        });

        jLabel6.setText("$");

        jButton1.setText("Kết thúc");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btn_batDau)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_batDau)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        jToolBar1.setRollover(true);

        jButton2.setText("Nhật kí");
        jButton2.setFocusable(false);
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jButton2);

        btn_capNhatThongTin.setText("Cập nhật thông tin");
        btn_capNhatThongTin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_capNhatThongTinActionPerformed(evt);
            }
        });
        jToolBar1.add(btn_capNhatThongTin);

        btn_kiemTra$.setText("Kiểm tra $");
        btn_kiemTra$.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_kiemTra$ActionPerformed(evt);
            }
        });
        jToolBar1.add(btn_kiemTra$);

        btn_themXe.setText("Thêm xe");
        btn_themXe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_themXeActionPerformed(evt);
            }
        });
        jToolBar1.add(btn_themXe);

        btn_xoaXe.setText("Xóa xe");
        btn_xoaXe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_xoaXeActionPerformed(evt);
            }
        });
        jToolBar1.add(btn_xoaXe);

        btn_dangXuat.setText("Đăng xuất");
        btn_dangXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_dangXuatActionPerformed(evt);
            }
        });
        jToolBar1.add(btn_dangXuat);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(104, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_kiemTra$ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_kiemTra$ActionPerformed
        try {
            dout.writeUTF("kiemtratien&"+tk);
        } catch (IOException ex) {
            Logger.getLogger(TaiXe.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_kiemTra$ActionPerformed

    private void btn_dangXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_dangXuatActionPerformed
        try {
            dout.writeUTF("dangxuat&taixe&"+tk);
        } catch (IOException ex) {
            Logger.getLogger(TaiXe.class.getName()).log(Level.SEVERE, null, ex);
        }
        dispose();
        System.exit(0);
    }//GEN-LAST:event_btn_dangXuatActionPerformed

    private void btn_xoaXeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_xoaXeActionPerformed
        new XoaXe(txid,bien,ip).setVisible(true);
    }//GEN-LAST:event_btn_xoaXeActionPerformed

    private void btn_themXeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_themXeActionPerformed
        new ThemXe(txid,ip).setVisible(true);
    }//GEN-LAST:event_btn_themXeActionPerformed

    private void btn_capNhatThongTinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_capNhatThongTinActionPerformed
        new update_taixe(txid,ip).setVisible(true);
    }//GEN-LAST:event_btn_capNhatThongTinActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void btn_ketThucActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ketThucActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_ketThucActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        try {
            dout.writeUTF("dangxuat&taixe&"+tk);
        } catch (IOException ex) {
            Logger.getLogger(TaiXe.class.getName()).log(Level.SEVERE, null, ex);
        }
        dispose();
        System.exit(0);
    }//GEN-LAST:event_formWindowClosing

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        if(evt.getClickCount() == 2) new ChiTiet(txid,ip).setVisible(true);
    }//GEN-LAST:event_jLabel3MouseClicked

    private void btn_batDauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_batDauActionPerformed
        if(tkkh.equalsIgnoreCase("")) JOptionPane.showMessageDialog(null, "Bạn chưa có khách hàng !");
        else {
            Date thoiGian = new Date();
            SimpleDateFormat dinhDangThoiGian = new SimpleDateFormat("HH:mm:ss dd/MM/yyyy");
            tbatdau = dinhDangThoiGian.format(thoiGian.getTime());
            try {
                dout.writeUTF("dienthongtin&"+tk+"&"+tkkh+"&"+diemdi+"&"+diemden);
            } catch (IOException ex) {
                Logger.getLogger(TaiXe.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btn_batDauActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(tkkh.equalsIgnoreCase("")) JOptionPane.showMessageDialog(null, "Bạn chưa có khách hàng !");
        else {
            Date thoiGian = new Date();
            SimpleDateFormat dinhDangThoiGian = new SimpleDateFormat("HH:mm:ss dd/MM/yyyy");
            String[] mang1,mang2;
            mang2 = tbatdau.split(" ");
            mang1 = mang2[0].split(":");
            int h1 = Integer.parseInt(mang1[0]);
            int m1 = Integer.parseInt(mang1[1]);
            int s1 = Integer.parseInt(mang1[2]);
            tketthuc = dinhDangThoiGian.format(thoiGian.getTime());
            String[] mang3,mang4;
            mang3 = tketthuc.split(" ");
            mang4 = mang3[0].split(":");
            int h2 = Integer.parseInt(mang4[0]);
            int m2 = Integer.parseInt(mang4[1]);
            int s2 = Integer.parseInt(mang4[2]);
            int thoigian = h2*60*60+m2*60+s2-h1*60*60-m1*60-s1;
            try {
                dout.writeUTF("danhgia&"+tk+"&"+bien+"&"+tkkh+"&"+tbatdau+"&"+tketthuc+"&"+diemdi+"&"+diemden+"&"+String.valueOf(thoigian));
                //dout.writeUTF("dienthongtinthem&"+tbatdau+"&"+tketthuc+);
            } catch (IOException ex) {
                Logger.getLogger(TaiXe.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TaiXe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TaiXe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TaiXe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TaiXe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
               // new TaiXe("levanminh@taixe","29MX456").setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_batDau;
    private javax.swing.JButton btn_capNhatThongTin;
    private javax.swing.JButton btn_dangXuat;
    private javax.swing.JButton btn_ketThuc;
    private javax.swing.JButton btn_kiemTra$;
    private javax.swing.JButton btn_themXe;
    private javax.swing.JButton btn_xoaXe;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables
}
